# Generated by Django 5.0.3 on 2024-03-18 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_pedido_oficina'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_do_pedido',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
