# Generated by Django 5.0.3 on 2024-03-21 14:31

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pedido_usuario_que_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='os_pdf',
            field=models.FileField(blank=True, default='', upload_to='', validators=[api.models.validandoPdf]),
        ),
    ]
